### PR TITLE
fix: cache:pool:prune fatals on a traced cache pool

### LINKED ISSUE #56: cache:pool:prune fatals: Call to undefined method TraceableCachePool::prune()
Hi everybody,

thanks a lot for this bundle! After upgrading to 3.0.0 I hit the following bug:

### Description

`cache:pool:prune` crashes with a fatal `Error` when cache tracing is enabled (the default) and a prunable cache pool is configured. The bundle decorates every `cache.pool` service with `TraceableCachePool`, which does not implement `prune()`, so the prune command calls a method that does not exist on the decorator.

### Environment

- PHP: 8.5.6
- Symfony: 8.0.13
- Bundle: 3.0.0

### Steps to reproduce

1. Configure a prunable pool as the app cache, e.g.:
   ```yaml
   framework:
       cache:
           app: cache.shared
           pools:
               cache.shared:
                   adapter: cache.adapter.doctrine_dbal
   ```
2. Leave cache tracing at its default (`open_telemetry.traces.cache.enabled: true`).
3. Run `bin/console cache:pool:prune`.

### Expected

Expired items are pruned from the prunable pool(s); the command exits 0.

### Actual

```
In CachePoolPruneCommand.php line 58:
  Attempted to call an undefined method named "prune" of class
  "Traceway\OpenTelemetryBundle\Cache\TraceableCachePool".
```

### Root cause

Symfony's `CachePoolPass` marks a prunable pool's `cache.pool` tag with `pruneable: true`. `DecoratorServicePass` transfers that tag onto the `TraceableCachePool` decorator, so `CachePoolPrunerPass` selects the decorator for pruning. `CachePoolPruneCommand` then calls `prune()` on it with no `method_exists` guard, but `TraceableCachePool` implements only `CacheInterface, AdapterInterface, ResetInterface` - no `PruneableInterface`, no `prune()`.

This hits anyone running the standard `cache:pool:prune` (e.g. on a schedule) against a DB-backed pool.

Small fix is already ready and will follow shortly.

### PR DESCRIPTION
**Pull request by pflueg**
`cache:pool:prune` fails with a fatal error when cache tracing is enabled (the default) and a prunable pool is configured - typically a DB-backed app cache. Since the command is usually run on a schedule, it surfaces as a recurring failure of the cleanup job rather than an interactive error.

The cause: Symfony tags prunable pools, and when a pool is wrapped for tracing, that tag is transferred onto `TraceableCachePool`. Symfony's pruner then selects the decorator and calls `prune()` on it - a method the decorator did not implement, resulting in `Call to undefined method ...TraceableCachePool::prune()`.

The fix follows Symfony's own `TraceableAdapter`: `TraceableCachePool` now implements `PruneableInterface` and delegates `prune()` to the wrapped pool, returning `false` when that pool is not prunable. The tag-aware and namespaced variants inherit the behaviour.

Two tests cover it - delegation to a prunable pool, and `false` for a non-prunable one. Full suite passes, PHPStan level 10 clean.

Fixes #56.

### CODE REVIEW

**Comment by jstojiljkovic** [comment]
Thanks, @pflueg, excellent fix.
Merged, shipping in the next patch. 🙏

**Comment by pflueg** [comment]
Thanks alot - especially for your work @jstojiljkovic !
