### ISSUE TITLE
cache:pool:prune fatals: Call to undefined method TraceableCachePool::prune()

### ISSUE THREAD

**Issue by pflueg** [tracewayapp/opentelemetry-symfony-bundle#56]
Hi everybody,

thanks a lot for this bundle! After upgrading to 3.0.0 I hit the following bug:

### Description

`cache:pool:prune` crashes with a fatal `Error` when cache tracing is enabled (the default) and a prunable cache pool is configured. The bundle decorates every `cache.pool` service with `TraceableCachePool`, which does not implement `prune()`, so the prune command calls a method that does not exist on the decorator.

### Environment

- PHP: 8.5.6
- Symfony: 8.0.13
- Bundle: 3.0.0

### Steps to reproduce

1. Configure a prunable pool as the app cache, e.g.:
   ```yaml
   framework:
       cache:
           app: cache.shared
           pools:
               cache.shared:
                   adapter: cache.adapter.doctrine_dbal
   ```
2. Leave cache tracing at its default (`open_telemetry.traces.cache.enabled: true`).
3. Run `bin/console cache:pool:prune`.

### Expected

Expired items are pruned from the prunable pool(s); the command exits 0.

### Actual

```
In CachePoolPruneCommand.php line 58:
  Attempted to call an undefined method named "prune" of class
  "Traceway\OpenTelemetryBundle\Cache\TraceableCachePool".
```

### Root cause

Symfony's `CachePoolPass` marks a prunable pool's `cache.pool` tag with `pruneable: true`. `DecoratorServicePass` transfers that tag onto the `TraceableCachePool` decorator, so `CachePoolPrunerPass` selects the decorator for pruning. `CachePoolPruneCommand` then calls `prune()` on it with no `method_exists` guard, but `TraceableCachePool` implements only `CacheInterface, AdapterInterface, ResetInterface` - no `PruneableInterface`, no `prune()`.

This hits anyone running the standard `cache:pool:prune` (e.g. on a schedule) against a DB-backed pool.

Small fix is already ready and will follow shortly.
